### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by WilliamKMLai** [CEGRcode/cookiecutter-biofrontend#3]
npm install works fine, but installs several highly vulnerable packages:

added 1743 packages from 885 contributors and audited 906950 packages in 19.591s
found 5 vulnerabilities (2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by PrashantKuntala** [comment]
Always update `Node` and `npm` to the latest LTS version,  in order to identify and report package vulnerabilities.
